# -*- coding: utf-8 -*-
"""BGK

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tj4med1jGTsGqdSpxWRYFxZnuVQIfqcJ
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib notebook

from k_means import KMeans

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
from skimage import io
import time
from mpl_toolkits.axes_grid1 import make_axes_locatable
from sklearn.cluster import KMeans as Kmeans_
from sklearn.metrics import mean_squared_error
import itertools
from sklearn.metrics import silhouette_samples, silhouette_score

data=pd.read_csv("spotifydata.csv", index_col="no")
data.head()

X=data[['acousticness', 'danceability']]

plt.close()
plt.style.use('seaborn')
plt.scatter(X['acousticness'], X['danceability'])
plt.xlabel('acousticness')
plt.ylabel('danceability')

model=KMeans(max_iter=300, tolerance=0.0001, n_clusters=5, runs=100)
(clusters, data_with_clusters)=model.fit(X)

model.cost_

plt.close()
for i, cluster_mean in enumerate(clusters):
  data_cluster_i=data_with_clusters[data_with_clusters[:, -1]==i]
  plt.scatter(data_cluster_i[:, 0], data_cluster_i[:, 1], label='Cluster '+str(i))
  plt.plot(cluster_mean[0], cluster_mean[1], label='Centroid '+str(i), marker='*', markersize=15, markeredgecolor="k", markeredgewidth=1)
  plt.xlabel('acousticness')
  plt.ylabel('danceability')
  plt.style.use('seaborn')
  plt.legend()

def elbow_method(X, max_k = 10):
    costs = []
    for k in range(2, max_k):
        model = KMeans(n_clusters=k, init_method='var_part')
        model.fit(X)
        costs.append(model.cost_)
    plt.close()
    plt.plot(list(range(2, max_k)), costs)
    plt.xlabel("# of clusters (K)")
    plt.ylabel("Cost")

elbow_method(X)

def draw_scatterplot(x_data, x_label, y_data, y_label):
    fig = plt.figure(figsize=(5,5))
    ax = fig.add_subplot(111)

    plt.xlim(0, 5)
    plt.ylim(0, 5)
    ax.set_xlabel(x_label)
    ax.set_ylabel(y_label)
    ax.scatter(x_data, y_data, s=30)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

draw_scatterplot(X['acousticness'], 'Acousticness', X['danceability'], 'Danceability')

import random
from kMedoids import kMedoidsPAM

mMtrix = [[random.uniform(X['acousticness'], X['danceability']) for j in range(8)] for i in range (20)]
medroidsNum = 8
InpAttNr = 7
oTT = 3

clustering = kMedoidsPAM(usageMatrice=mMtrix, k=medroidsNum, nbrImprovementAttempts=InpAttNr, outliersThresholdTraitement=oTT)
print(clustering)

